version: "3"

services:
  adjutant-moc:
    container_name: adjutant-moc
    image: massopencloud/adjutant-moc:r4
    environment:
      SECRET_KEY: {{ secret_key }}
      DB_USER: adjutant
      DB_HOST: "{{ docker_host_ip }}"
      DB_PASSWORD: "{{ db_password }}"
      OPENSTACK_AUTH_URL: https://kaizen.massopen.cloud:13000/v3
      OPENSTACK_USERNAME: onboarding
      OPENSTACK_PASSWORD: {{ openstack_password }}
      OPENSTACK_PROJECT: admin
      EMAIL_HOST: mail.massopen.cloud
      EMAIL_USERNAME: onboarding@massopen.cloud
      EMAIL_PASSWORD: {{ email_password }}
      EMAIL_PORT: 25
      PUBLIC_NETWORK_ID: "71b97520-69af-4c35-8153-cdf827d96e60"
    ports:
      - "8081:8080"  # host:container
    volumes:
      - "./ssh:/.ssh"
